# Generated by Django 2.1.7 on 2019-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='historicalauthor',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='historicalnewsletterauthor',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='historicalopinionarticleauthor',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='historicalprofessionalcommentator',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='historicalreporter',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='usersfollowingauthors',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
    ]
