# Generated by Django 2.2.1 on 2019-05-06 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinfo',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='active_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Active at'),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
