# Generated by Django 2.1.7 on 2019-04-25 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoccerCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Status')),
                ('active_at', models.DateTimeField(blank=True, null=True, verbose_name='Active at')),
                ('inactive_at', models.DateTimeField(blank=True, null=True, verbose_name='Inactive at')),
                ('sort_order', models.IntegerField(blank=True, unique=True, verbose_name='Order value')),
                ('api_id', models.IntegerField()),
                ('api_name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoccerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Status')),
                ('active_at', models.DateTimeField(blank=True, null=True, verbose_name='Active at')),
                ('inactive_at', models.DateTimeField(blank=True, null=True, verbose_name='Inactive at')),
                ('sort_order', models.IntegerField(blank=True, unique=True, verbose_name='Order value')),
                ('api_title', models.CharField(max_length=256)),
                ('api_embed', models.TextField(max_length=256)),
                ('api_thumbnail_url', models.URLField()),
                ('inserted_title', models.CharField(blank=True, max_length=256, null=True)),
                ('inserted_description', models.TextField(blank=True, null=True)),
                ('inserted_thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoccerTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Status')),
                ('active_at', models.DateTimeField(blank=True, null=True, verbose_name='Active at')),
                ('inactive_at', models.DateTimeField(blank=True, null=True, verbose_name='Inactive at')),
                ('sort_order', models.IntegerField(blank=True, unique=True, verbose_name='Order value')),
                ('api_name', models.CharField(max_length=256)),
                ('min_icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('medium_icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('big_icon', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoccerVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_title', models.CharField(max_length=256)),
                ('api_embed', models.TextField()),
                ('inserted_title', models.CharField(blank=True, max_length=256, null=True)),
                ('inserted_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='soccermatch',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_match', to='sports.SoccerTeam'),
        ),
        migrations.AddField(
            model_name='soccermatch',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.SoccerCompetition'),
        ),
        migrations.AddField(
            model_name='soccermatch',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_match', to='sports.SoccerTeam'),
        ),
    ]
