# Generated by Django 2.1.7 on 2019-04-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soccercompetition',
            name='inserted_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
