# Generated by Django 2.1.7 on 2019-04-25 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_soccercompetition_inserted_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFootballCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Status')),
                ('active_at', models.DateTimeField(blank=True, null=True, verbose_name='Active at')),
                ('inactive_at', models.DateTimeField(blank=True, null=True, verbose_name='Inactive at')),
                ('sort_order', models.IntegerField(blank=True, unique=True, verbose_name='Order value')),
                ('api_id', models.IntegerField()),
                ('api_name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiFootballLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Status')),
                ('active_at', models.DateTimeField(blank=True, null=True, verbose_name='Active at')),
                ('inactive_at', models.DateTimeField(blank=True, null=True, verbose_name='Inactive at')),
                ('sort_order', models.IntegerField(blank=True, unique=True, verbose_name='Order value')),
                ('api_id', models.IntegerField()),
                ('api_name', models.CharField(max_length=256)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.ApiFootballCountry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiFootballStading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Status')),
                ('active_at', models.DateTimeField(blank=True, null=True, verbose_name='Active at')),
                ('inactive_at', models.DateTimeField(blank=True, null=True, verbose_name='Inactive at')),
                ('sort_order', models.IntegerField(blank=True, unique=True, verbose_name='Order value')),
                ('season', models.CharField(max_length=9)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.ApiFootballLeague')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiFootballTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Status')),
                ('active_at', models.DateTimeField(blank=True, null=True, verbose_name='Active at')),
                ('inactive_at', models.DateTimeField(blank=True, null=True, verbose_name='Inactive at')),
                ('sort_order', models.IntegerField(blank=True, unique=True, verbose_name='Order value')),
                ('api_name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiFootballTeamStading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_league_position', models.IntegerField(default=0)),
                ('overall_league_payed', models.IntegerField(default=0)),
                ('overall_league_W', models.IntegerField(default=0)),
                ('overall_league_D', models.IntegerField(default=0)),
                ('overall_league_L', models.IntegerField(default=0)),
                ('overall_league_GF', models.IntegerField(default=0)),
                ('overall_league_GA', models.IntegerField(default=0)),
                ('overall_league_PTS', models.IntegerField(default=0)),
                ('home_league_position', models.IntegerField(default=0)),
                ('home_league_payed', models.IntegerField(default=0)),
                ('home_league_W', models.IntegerField(default=0)),
                ('home_league_D', models.IntegerField(default=0)),
                ('home_league_L', models.IntegerField(default=0)),
                ('home_league_GF', models.IntegerField(default=0)),
                ('home_league_GA', models.IntegerField(default=0)),
                ('home_league_PTS', models.IntegerField(default=0)),
                ('away_league_position', models.IntegerField(default=0)),
                ('away_league_payed', models.IntegerField(default=0)),
                ('away_league_W', models.IntegerField(default=0)),
                ('away_league_D', models.IntegerField(default=0)),
                ('away_league_L', models.IntegerField(default=0)),
                ('away_league_GF', models.IntegerField(default=0)),
                ('away_league_GA', models.IntegerField(default=0)),
                ('away_league_PTS', models.IntegerField(default=0)),
                ('stading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.ApiFootballStading')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.ApiFootballTeam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='apifootballstading',
            name='teams',
            field=models.ManyToManyField(through='sports.ApiFootballTeamStading', to='sports.ApiFootballTeam'),
        ),
    ]
