# Generated by Django 2.1.7 on 2019-04-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_auto_20190425_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apifootballcountry',
            name='api_id',
        ),
    ]
