# Generated by Django 2.1.7 on 2019-04-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_remove_apifootballcountry_api_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFootballSeason',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=256)),
                ('start_date', models.CharField(max_length=256)),
                ('end_date', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
