# Generated by Django 2.1.7 on 2019-04-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_apifootballseasson'),
    ]

    operations = [
        migrations.AddField(
            model_name='apifootballcountry',
            name='api_code',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apifootballleague',
            name='flag',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apifootballleague',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apifootballleague',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sports.ApiFootballSeason'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apifootballleague',
            name='standings',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
