# Generated by Django 2.1.7 on 2019-04-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_auto_20190425_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='apifootballteam',
            name='api_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apifootballteam',
            name='code',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apifootballteam',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
