# Generated by Django 2.1.7 on 2019-04-25 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_auto_20190425_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFootballEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elapsed', models.IntegerField()),
                ('event_type', models.CharField(max_length=256)),
                ('detail', models.CharField(max_length=256)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.ApiFootballPlayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.ApiFootballTeam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiFootballFixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture_id', models.IntegerField()),
                ('event_timestamp', models.IntegerField()),
                ('event_date', models.CharField(max_length=256)),
                ('league_round', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('statusShort', models.CharField(max_length=256)),
                ('goalsHomeTeam', models.IntegerField()),
                ('goalsAwayTeam', models.IntegerField()),
                ('halftime_score', models.CharField(max_length=256)),
                ('final_score', models.CharField(max_length=256)),
                ('penalty', models.CharField(blank=True, max_length=256, null=True)),
                ('elapsed', models.CharField(max_length=256)),
                ('firstHalfStart', models.CharField(max_length=256)),
                ('secondHalfStart', models.CharField(max_length=256)),
                ('awayTeam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='sports.ApiFootballTeam')),
                ('homeTeam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='sports.ApiFootballTeam')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.ApiFootballLeague')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
