# Generated by Django 2.1.7 on 2019-04-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_apifootballevent_apifootballfixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLineupGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_team_formation', models.CharField(max_length=256)),
                ('away_team_formation', models.CharField(max_length=256)),
                ('away_team_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_game', to='sports.ApiFootballCoach')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.ApiFootballFixture')),
                ('home_team_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_game', to='sports.ApiFootballCoach')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiLineUpPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('number', models.IntegerField()),
                ('is_sub', models.BooleanField(default=False)),
                ('line_up_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.ApiLineupGame')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
