# Generated by Django 2.1.7 on 2019-04-25 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0012_apilineupgame_apilineupplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFixtureStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiTeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiTeamStatsConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.IntegerField(default=0)),
                ('away', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assists', models.IntegerField(default=0)),
                ('blocked_shots', models.IntegerField(default=0)),
                ('corner_kicks', models.IntegerField(default=0)),
                ('counter_attacks', models.IntegerField(default=0)),
                ('cross_attacks', models.IntegerField(default=0)),
                ('fouls', models.IntegerField(default=0)),
                ('free_kicks', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('goal_attempts', models.IntegerField(default=0)),
                ('offsides', models.IntegerField(default=0)),
                ('ball_possession', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('goalkeeper_saves', models.IntegerField(default=0)),
                ('shots_off_goal', models.IntegerField(default=0)),
                ('shots_on_goal', models.IntegerField(default=0)),
                ('substitutions', models.IntegerField(default=0)),
                ('throwins', models.IntegerField(default=0)),
                ('medical_treatment', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='apilineupplayer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiteamstats',
            name='draws',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AddField(
            model_name='apiteamstats',
            name='goals_against',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AddField(
            model_name='apiteamstats',
            name='goals_avg_against',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AddField(
            model_name='apiteamstats',
            name='goals_avg_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AddField(
            model_name='apiteamstats',
            name='goals_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AddField(
            model_name='apiteamstats',
            name='loses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AddField(
            model_name='apiteamstats',
            name='matchs_played',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AddField(
            model_name='apiteamstats',
            name='wins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AddField(
            model_name='apifixturestats',
            name='away_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixture', to='sports.Stats'),
        ),
        migrations.AddField(
            model_name='apifixturestats',
            name='home_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixture', to='sports.Stats'),
        ),
    ]
