# Generated by Django 2.1.7 on 2019-04-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0013_auto_20190425_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apifootballfixture',
            old_name='awayTeam_id',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='apifootballfixture',
            old_name='firstHalfStart',
            new_name='first_half_start',
        ),
        migrations.RenameField(
            model_name='apifootballfixture',
            old_name='goalsAwayTeam',
            new_name='goals_away_team',
        ),
        migrations.RenameField(
            model_name='apifootballfixture',
            old_name='goalsHomeTeam',
            new_name='goals_home_team',
        ),
        migrations.RenameField(
            model_name='apifootballfixture',
            old_name='homeTeam_id',
            new_name='home_team',
        ),
        migrations.RenameField(
            model_name='apifootballfixture',
            old_name='secondHalfStart',
            new_name='second_half_start',
        ),
        migrations.RenameField(
            model_name='apifootballfixture',
            old_name='statusShort',
            new_name='status_short',
        ),
        migrations.AlterField(
            model_name='apifootballevent',
            name='player',
            field=models.CharField(max_length=256),
        ),
    ]
