# Generated by Django 2.1.7 on 2019-04-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('sports', '0014_auto_20190425_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='ApiStatus',
        ),
        migrations.AddField(
            model_name='apilineupgame',
            name='away_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='sports.ApiFootballTeam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apilineupgame',
            name='home_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='sports.ApiFootballTeam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apilineupplayer',
            name='team',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='sports.ApiFootballTeam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiteamstats',
            name='league',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='sports.ApiFootballLeague'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiteamstats',
            name='team',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='sports.ApiFootballTeam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apiteamstats',
            name='draws',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AlterField(
            model_name='apiteamstats',
            name='goals_against',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AlterField(
            model_name='apiteamstats',
            name='goals_avg_against',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AlterField(
            model_name='apiteamstats',
            name='goals_avg_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AlterField(
            model_name='apiteamstats',
            name='goals_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AlterField(
            model_name='apiteamstats',
            name='loses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
        migrations.AlterField(
            model_name='apiteamstats',
            name='matchs_played',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='sports.ApiTeamStatsConditions'),
        ),
    ]
