# Generated by Django 2.1.7 on 2019-04-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0015_auto_20190425_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiteamstats',
            old_name='matchs_played',
            new_name='matches_played',
        ),
    ]
