# Generated by Django 2.1.7 on 2019-04-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0016_auto_20190425_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='apifootballseason',
            name='api_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apifootballleague',
            name='standings',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
