# Generated by Django 2.1.7 on 2019-04-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0017_auto_20190427_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apifootballstanding',
            name='group',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
