# Generated by Django 2.1.7 on 2019-04-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0021_soccervideo_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apifootballseason',
            name='api_id',
        ),
    ]
