# Generated by Django 2.1.7 on 2019-04-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0022_remove_apifootballseason_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apifootballevent',
            name='team',
            field=models.CharField(max_length=256),
        ),
    ]
