# Generated by Django 2.1.7 on 2019-04-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0023_auto_20190427_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apifootballevent',
            old_name='team',
            new_name='team_name',
        ),
    ]
