# Generated by Django 2.1.7 on 2019-04-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0024_auto_20190427_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilineupgame',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='apilineupgame',
            name='home_team',
        ),
    ]
