# Generated by Django 2.1.7 on 2019-04-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0026_auto_20190427_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apifootballfixture',
            old_name='fixture_id',
            new_name='api_id',
        ),
    ]
