# Generated by Django 2.1.7 on 2019-04-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0027_auto_20190427_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiteamstatsconditions',
            name='away',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='apiteamstatsconditions',
            name='home',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='apiteamstatsconditions',
            name='total',
            field=models.FloatField(default=0, null=True),
        ),
    ]
