# Generated by Django 2.1.7 on 2019-04-09 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicopinionarticle',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='basicreporterarticle',
            name='search_image',
        ),
    ]
