# Generated by Django 2.1.7 on 2019-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190409_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicopinionarticle',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='basicreporterarticle',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='role',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
    ]
