# Generated by Django 2.1.7 on 2019-04-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('comments', '0002_auto_20190408_2253'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='users',
        ),
        migrations.RemoveField(
            model_name='newslettermessage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='newslettermessage',
            name='newsletter',
        ),
        migrations.RemoveField(
            model_name='newslettermessage',
            name='template',
        ),
        migrations.RemoveField(
            model_name='newslettermessage',
            name='users',
        ),
        migrations.RemoveField(
            model_name='newslettermessageuser',
            name='newsletter_message',
        ),
        migrations.RemoveField(
            model_name='newslettermessageuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='newsletter',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='template',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='NewsletterMessage',
        ),
        migrations.DeleteModel(
            name='NewsletterMessageUser',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscription',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
