# Generated by Django 2.1.7 on 2019-04-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettermessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', related_query_name='message', to='newsletter.Template', verbose_name='User'),
        ),
    ]
