# Generated by Django 2.1.7 on 2019-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_auto_20190408_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
    ]
