# Generated by Django 2.1.7 on 2019-04-08 22:32

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_auto_20190408_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
