# Generated by Django 2.1.7 on 2019-04-08 22:42

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_auto_20190408_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taxonomy.SectionTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
