# Generated by Django 2.1.7 on 2019-04-08 22:45

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0006_auto_20190408_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='taxonomy.Section'),
        ),
    ]
