# Generated by Django 2.1.7 on 2019-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0008_auto_20190408_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='historicalsection',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='section',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='usersfollowingsection',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
    ]
