# Generated by Django 2.1.7 on 2019-04-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_auto_20190419_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookgroup',
            name='streams',
        ),
        migrations.RemoveField(
            model_name='facebookpage',
            name='streams',
        ),
        migrations.AddField(
            model_name='facebookstream',
            name='groups',
            field=models.ManyToManyField(related_name='streams', related_query_name='streams', through='multimedia.FacebookLiveStreamGroup', to='multimedia.FacebookGroup'),
        ),
        migrations.AddField(
            model_name='facebookstream',
            name='pages',
            field=models.ManyToManyField(related_name='pages', related_query_name='pages', through='multimedia.FacebookLiveStreamPage', to='multimedia.FacebookPage'),
        ),
    ]
