# Generated by Django 2.1.7 on 2019-04-19 21:58

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0003_auto_20190419_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookstream',
            name='groups',
            field=modelcluster.fields.ParentalManyToManyField(related_name='streams', related_query_name='streams', through='multimedia.FacebookLiveStreamGroup', to='multimedia.FacebookGroup'),
        ),
        migrations.AlterField(
            model_name='facebookstream',
            name='pages',
            field=modelcluster.fields.ParentalManyToManyField(related_name='pages', related_query_name='pages', through='multimedia.FacebookLiveStreamPage', to='multimedia.FacebookPage'),
        ),
    ]
