# Generated by Django 2.1.7 on 2019-04-19 22:00

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_auto_20190419_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookstream',
            name='pages',
            field=modelcluster.fields.ParentalManyToManyField(related_name='streams', related_query_name='streams', through='multimedia.FacebookLiveStreamPage', to='multimedia.FacebookPage'),
        ),
    ]
