# Generated by Django 2.1.7 on 2019-04-19 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0007_auto_20190419_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'base_manager_name': 'objects'},
        ),
    ]
