# Generated by Django 2.1.7 on 2019-04-19 22:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('multimedia', '0008_auto_20190419_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tagmanagment',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='tagmanagment',
            name='tag',
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='multimedia.TagManagement', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='TagManagment',
        ),
        migrations.AddField(
            model_name='tagmanagement',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='multimedia.Media'),
        ),
        migrations.AddField(
            model_name='tagmanagement',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_tagmanagement_items', to='taggit.Tag'),
        ),
    ]
