# Generated by Django 2.1.7 on 2019-04-19 22:32

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0009_auto_20190419_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooklivestreamgroup',
            name='facebook_group',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.FacebookGroup'),
        ),
        migrations.AlterField(
            model_name='facebooklivestreamgroup',
            name='facebook_stream',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.FacebookStream'),
        ),
        migrations.AlterField(
            model_name='facebooklivestreampage',
            name='facebook_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.FacebookPage'),
        ),
        migrations.AlterField(
            model_name='facebooklivestreampage',
            name='facebook_stream',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.FacebookStream'),
        ),
    ]
