# Generated by Django 2.1.7 on 2019-04-19 23:11

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0012_auto_20190419_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooklivestreamgroup',
            name='facebook_stream',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_group_relationship', to='multimedia.FacebookStream'),
        ),
        migrations.AlterField(
            model_name='facebooklivestreampage',
            name='facebook_stream',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_page_relationship', to='multimedia.FacebookStream'),
        ),
    ]
