# Generated by Django 2.1.7 on 2019-04-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0013_auto_20190419_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookstream',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='facebookstream',
            name='pages',
        ),
    ]
