# Generated by Django 2.1.7 on 2019-04-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('multimedia', '0014_auto_20190419_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklivestreamgroup',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_multimedia.facebooklivestreamgroup_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='facebooklivestreampage',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_multimedia.facebooklivestreampage_set+', to='contenttypes.ContentType'),
        ),
    ]
