# Generated by Django 2.1.7 on 2019-04-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0015_auto_20190420_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebooklivestreamgroup',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='facebooklivestreampage',
            name='polymorphic_ctype',
        ),
    ]
