# Generated by Django 2.1.7 on 2019-04-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0016_auto_20190420_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooklivestreamgroup',
            name='active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='facebooklivestreampage',
            name='active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Status'),
        ),
    ]
