# Generated by Django 2.1.7 on 2019-04-08 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportercomment',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comments', to='users.Reporter'),
        ),
        migrations.AddField(
            model_name='professionalcomment',
            name='commentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comments', to='users.ProfessionalCommentator'),
        ),
        migrations.AddField(
            model_name='normalcomment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comments', to='users.Client'),
        ),
        migrations.AddField(
            model_name='normalcomment',
            name='marked_as_spam_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
