# Generated by Django 2.1.7 on 2019-04-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190408_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentstatus',
            name='status',
            field=models.CharField(choices=[(2, 'Draft'), (1, 'Pending'), (3, 'Accepted'), (4, 'Refused')], default=2, max_length=32, verbose_name='status'),
        ),
    ]
