# Generated by Django 2.1.7 on 2019-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20190417_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentstatus',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
    ]
