# Generated by Django 2.1.7 on 2019-04-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20190417_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='children', to='comments.Comment'),
        ),
    ]
