# Generated by Django 2.1.7 on 2019-04-19 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Status')),
                ('active_at', models.DateTimeField(blank=True, null=True, verbose_name='Active at')),
                ('inactive_at', models.DateTimeField(blank=True, null=True, verbose_name='Inactive at')),
                ('sort_order', models.IntegerField(blank=True, unique=True, verbose_name='Order value')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('zoom', models.IntegerField(verbose_name='Zoom')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='CasesOfTheDay',
            fields=[
                ('locatedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cases_of_the_day.LocatedModel')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('cases_of_the_day.locatedmodel',),
        ),
        migrations.CreateModel(
            name='Locals',
            fields=[
                ('locatedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cases_of_the_day.LocatedModel')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('cases_of_the_day.locatedmodel',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('locatedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cases_of_the_day.LocatedModel')),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Symbol')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('cases_of_the_day.locatedmodel',),
        ),
        migrations.AddField(
            model_name='locatedmodel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_cases_of_the_day.locatedmodel_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='locals',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases_of_the_day.Region'),
        ),
    ]
