# Generated by Django 2.1.7 on 2019-04-19 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multimedia', '0002_auto_20190419_1802'),
        ('cases_of_the_day', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesoftheday',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.Media', verbose_name='Media'),
        ),
    ]
