# Generated by Django 2.1.7 on 2019-04-18 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190418_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Publish Date'),
        ),
    ]
