# Generated by Django 2.1.7 on 2019-04-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_maps_key', models.CharField(max_length=256, verbose_name='Google Maps Key')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readers_letter_email', models.CharField(max_length=64, verbose_name="Reader's letter email")),
                ('redaction_email', models.CharField(max_length=64, verbose_name='Redaction Email')),
                ('publish_email', models.CharField(max_length=64, verbose_name='Publish Email')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnterpriseSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=32, verbose_name='Street')),
                ('zip_code', models.CharField(max_length=32, verbose_name='Street')),
                ('city', models.CharField(max_length=32, verbose_name='City')),
                ('country', models.CharField(max_length=32, verbose_name='Country')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalServiceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liveblog_url', models.URLField(verbose_name='Liveblog Url')),
                ('initiatives_url', models.URLField(verbose_name='Initiatives Url')),
                ('editions_url', models.URLField(verbose_name='Editions Url')),
                ('subscriptions_url', models.URLField(verbose_name='Subscriptions Url')),
                ('malta_url', models.URLField(verbose_name='Malta Url')),
                ('dcs_url', models.URLField(verbose_name='DCS URL')),
                ('magazine_D7_url', models.URLField(verbose_name='Magazine D7 Url')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(help_text='Your Facebook page URL')),
                ('facebook_access_token', models.CharField(max_length=64, verbose_name='Facebook access token')),
                ('instagram', models.URLField(help_text='Your Instagram URL')),
                ('youtube', models.URLField(help_text='Your YouTube channel or user account URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelephoneContactSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretariat_contact_telephone', models.CharField(max_length=32, verbose_name='Secretariat Telephone')),
                ('geral_contact_telephone', models.CharField(max_length=32, verbose_name='Geral Telephone')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
