# Generated by Django 2.1.7 on 2019-04-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='facebook_page_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Facebook Page Id'),
        ),
    ]
