# Generated by Django 2.2.1 on 2019-05-06 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerole',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='servicerole',
            name='active_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Active at'),
        ),
        migrations.AddField(
            model_name='servicerole',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactive at'),
        ),
        migrations.AlterField(
            model_name='role',
            name='services',
            field=models.ManyToManyField(through='roles.ServiceRole', to='client.ServiceInfo'),
        ),
        migrations.AlterField(
            model_name='servicerole',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.ServiceInfo'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
